### ISSUE TITLE
ProductCreated can be published for existed products

### ISSUE THREAD

**Issue by ljubchyk** [VaughnVernon/IDDD_Samples_NET#26]
Hello guys

With current implementation we are publishing ProductCreated domain event in ctor for product. 
If we will implement IProductRepository and use EF Core than this ctor will be called on read **existed** product from db. 

Is ctor a good place to decide that new **instance** of product is created for **new** product? 

Some ctor will be called when product will be readed from db or deserialized from json (let's for example we are working with json files as storage) and what ctor exactly depeneds on implementation of repository or ORM conventions. 

https://github.com/VaughnVernon/IDDD_Samples_NET/blob/90fcc52d9c1af29640ec2a8a3e0e7c692f3e6663/iddd_agilepm/Domain.Model/Products/Product.cs#L46

**Comment by joalcava** [comment]
If you add a default constructor (No parametes) and make it private or protected EF Core will use it and will not call your other constructos which may contain bussines logic like the event.

**Comment by VaughnVernon** [comment]
Yes, that is the intent with ORM. Using Gson serialization, the implicit zero-arg ctor is used.

**Comment by ljubchyk** [comment]
yes, contrary to the documentation ef core will call default constructor. same as json serializators

thanks
